### ISSUE TITLE
文件中的註解要如何在目前的模板中做到？

### ISSUE THREAD

**Issue by jerome-cjko** [TBIA/docs#22]
如[資料標準](https://github.com/TBIA/docs/blob/main/docs/biodiversity_data_standard.md)的第七頁
要麻煩思賢找解法

**Comment by moogoo78** [comment]
可以做到，文件: https://tbia.github.io/docs/#footnote

已經commit了
https://github.com/TBIA/docs/commit/153076d790b99b32308497faec8bea310dfdb9ce
