### ISSUE TITLE
冒號＆分號要採用全形還是半形？

### ISSUE THREAD

**Issue by jerome-cjko** [TBIA/docs#26]
直接複製原始文字常常是半形

**Comment by jerome-cjko** [comment]
建議以文件主體的語言決定全形或半形：

文件主體語言為中文：全形
文件主體語言為英文：半形

**Comment by jerome-cjko** [comment]
@jinyinglee 依據上次決定更新資料標準文件
@jerome-cjko 寫進指引

**Comment by jinyinglee** [comment]
@jerome-cjko 我（不小心）新增到指引裡了，現在是加一個新的區塊「文件撰寫建議」，看你覺得合不合適

**Comment by jerome-cjko** [comment]
被 @jinyinglee  照顧到 🥹 沒有問題喔！也可以準備關掉惹
