### ISSUE TITLE
圖片要如何置中？

### ISSUE THREAD

**Issue by jerome-cjko** [TBIA/docs#28]
可能也要用html的格式撰寫？

**Comment by moogoo78** [comment]
有對齊的語法可以使用，還沒試過
https://squidfunk.github.io/mkdocs-material/reference/images/

**Comment by jerome-cjko** [comment]
這個可以麻煩 @jinyinglee 試試看嗎？

**Comment by jinyinglee** [comment]
資料標準圖片已置中
指引也有補上置中語法（用html格式撰寫）

**Comment by moogoo78** [comment]
啊啊啊 我們同時改了同樣的地方XD
