### ISSUE TITLE
自動產生的作者一和作者二是否確定這樣呈現？

### ISSUE THREAD

**Issue by jerome-cjko** [TBIA/docs#31]
兩個資訊需要再討論

**Comment by jerome-cjko** [comment]
要不要都先參考GBIF，就是放上作者，但除了秘書處是作者會放上email外，其他個人作者就不放上email？

https://docs.gbif.org/documentation-guidelines/en/
https://docs.gbif.org/georeferencing-quick-reference-guide/1.0/en/

**Comment by jerome-cjko** [comment]
確定以下作法：

- 只有一個作者欄（刪掉作者二）
- 版本改成 version
- 作者欄內容都是自己打
- 作者如果為秘書處要附上email

以上寫進指引。

**Comment by jerome-cjko** [comment]
請 @moogoo78 試試看有沒有文件的metadata撰寫方式

**Comment by jerome-cjko** [comment]
參考做法：
https://github.com/moogoo78/mg-docs/blob/main/docs/blog/articles/231104many-browsers.md?plain=1

```
---
date: 2023-11-04
title: 試用各種瀏覽器(2023)
slug: try-some-browsers
categories:
  - Tech
  - Review
---
```

**Comment by jerome-cjko** [comment]
再請 ＠moogoo78 試一次，下次會議若無解就先用手動。

**Comment by moogoo78** [comment]
> 再請 @moogoo78 試一次，下次會議若無解就先用手動。

這個套件似乎要付費
https://squidfunk.github.io/mkdocs-material/plugins/meta/

**Comment by jerome-cjko** [comment]
先用手動貼上。

改指引和模板作者是文件工作小組
