### ISSUE TITLE
首頁跟指引目前是2個檔案，容易搞混

### ISSUE THREAD

**Issue by moogoo78** [TBIA/docs#38]
在`docs`目錄裡面有[index.md](https://github.com/TBIA/docs/blob/main/docs/index.md)，跟[TBIA 文件指引 Guidelines（草稿）.md](https://github.com/TBIA/docs/blob/main/docs/TBIA%20%E6%96%87%E4%BB%B6%E6%8C%87%E5%BC%95%20Guidelines%EF%BC%88%E8%8D%89%E7%A8%BF%EF%BC%89.md)，兩個檔案，有87%像，需要整理合併一下。

**Comment by jerome-cjko** [comment]
決定把 index.md 刪掉
把 [TBIA 文件指引 Guidelines（草稿）.md](https://github.com/TBIA/docs/blob/main/docs/TBIA%20%E6%96%87%E4%BB%B6%E6%8C%87%E5%BC%95%20Guidelines%EF%BC%88%E8%8D%89%E7%A8%BF%EF%BC%89.md) 列為首頁預設文件

@moogoo78

**Comment by jinyinglee** [comment]
因為不能將其他文件預設為首頁，所以還是以index.md為首頁
