### ISSUE TITLE
指引的「有序清單」最上層在顯示時是「*」跟無序清單一樣，正確嗎？

### ISSUE THREAD

**Issue by jerome-cjko** [TBIA/docs#39]
https://tbia.github.io/docs/TBIA%20%E6%96%87%E4%BB%B6%E6%8C%87%E5%BC%95%20Guidelines%EF%BC%88%E8%8D%89%E7%A8%BF%EF%BC%89/#_11

**Comment by jinyinglee** [comment]
已拆開成兩個區塊
