### ISSUE TITLE
2024-01-25 project close out meeting

### ISSUE THREAD

**Issue by jerome-cjko** [TBIA/docs#41]
1. close all related issues
2. 所有人讀過一次指引 + 模板
3. check if all four documents fit 指引 + 模板（一人分配一個 document，要看不是自己撰寫的那份）
4. other issues

**Comment by jinyinglee** [comment]
文件模板
- 缺PDF版本
- 永久統一資源標籤 Persistent URI：說明文字可能要再修改
- 引言的內文感覺可以調整，目前有點長＆感覺不太符合我們的文件類型
- 引用文獻 References 需不需要有說明＆範例
- 有些區塊的內文是範例（如詞彙表），有些是說明文字（如附錄一）

**Comment by jinyinglee** [comment]
文件指引
- 現有文件的待補URI（不確定要放什麼
- 完成一個文件的步驟：需不需要補上公布的流程（需要修改mkdocs.yml 的目錄，把文件連結放上去）？
- 給編輯們、本文件網站的軟體架構、給TBIA工程師們的資訊 - 文件架構 尚未完成
- 版權說明 Colophon 的TBIA秘書處是不是要改寫成文件工作小組？

**Comment by jinyinglee** [comment]
.md文件檔名需不需要有統一格式？需不需要再有資料夾分類？（像是分開 指引模版 ＆ 文件）

**Comment by g11145590** [comment]
指引中的圖片說明順序感覺很混亂

**Comment by jerome-cjko** [comment]
未完成

- [ ] 引用文獻 References 需不需要有說明＆範例： @g11145590 
- [ ] 有些區塊的內文是範例（如詞彙表），有些是說明文字（如附錄一）： @g11145590 
- [ ] 本文件網站的軟體架構、給TBIA工程師們的資訊 - 文件架構： @moogoo78 
- [ ] .md文件檔名需不需要有統一格式 統一改成英文： @jerome-cjko 
- [ ] 指引中的圖片說明順序感覺很混亂： @jerome-cjko

**Comment by jerome-cjko** [comment]
2024-02-01
- [ ] 指引的h5（如Markdown語法的「標題」）等字體小於內文
